### ISSUE TITLE
"rqt_gui: error: unrecognized arguments" and exits

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#12]
I've tried -v, -b etc.

```
user@machinechang:~/repo/rqt/rqt_gui$ rosrun rqt_gui rqt_gui -v &
[1] 15642
user@machinechang:~/repo/rqt/rqt_gui$ QtBindingHelper using pyqt
PerspectiveManager.switch_perspective() switching to perspective "Default"
MainWindow.restore_settings()
PluginManager.restore_settings()
PluginManager.restore_settings() loading 1 plugins
RosPyPluginProvider._init_node() initialize ROS node "rqt_gui_py_node_15642"
usage: rqt_gui [-h] [-u ROS_MASTER_URI]
rqt_gui: error: unrecognized arguments: -v

[1]+  Exit 2                  rosrun rqt_gui rqt_gui -v
user@machinechang:~/repo/rqt/rqt_gui$ rosrun rqt_gui rqt_gui --qt-binding pyside &
[1] 15685
user@machinechang:~/repo/rqt/rqt_gui$ Could not import "pyside" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/u/isaito/repo/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    import libqt_gui_cpp_shiboken
ImportError: No module named libqt_gui_cpp_shiboken

usage: rqt_gui [-h] [-u ROS_MASTER_URI]
rqt_gui: error: unrecognized arguments: --qt-binding pyside

[1]+  Exit 2                  rosrun rqt_gui rqt_gui --qt-binding pyside
user@machinechang:~/repo/rqt/rqt_gui$ rosrun rqt_gui rqt_gui -b pyside &
[1] 15701
user@machinechang:~/repo/rqt/rqt_gui$ Could not import "pyside" bindings of qt_gui_cpp library - so C++ plugins will not be available:
Traceback (most recent call last):
  File "/u/isaito/repo/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp/cpp_binding_helper.py", line 43, in <module>
    import libqt_gui_cpp_shiboken
ImportError: No module named libqt_gui_cpp_shiboken

usage: rqt_gui [-h] [-u ROS_MASTER_URI]
rqt_gui: error: unrecognized arguments: -b pyside
```

Don't know yet the relationship with this (http://goo.gl/eQtJx) change.

**Comment by dirk-thomas** [comment]
The described behavior is not reproduable. Please describe in more detail which version of qt_gui_core and rqt you are using.

**Comment by 130s** [comment]
Sorry not to have listed revisions, and the phenomenon stopped on the same machine either.
Checked with qt_gui_core 682957cbe76a2e3c67a2b1c00e4c8c69de86dcbb
