### ISSUE TITLE
Segmentation fault on any rqt related tool

### ISSUE THREAD

**Issue by miquelmassot** [ros-visualization/rqt#122]
ROS Kinetic on Ubuntu 16.04
    
    gdb --args python /opt/ros/kinetic/bin/rqt 

returns

```
#0  0x0000000000000000 in ?? ()
#1  0x00007fffbfdbc667 in ?? () from /opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui_cpp/libqt_gui_cpp_sip.so
#2  0x00007fffef074811 in ?? () from /usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so
#3  0x00007fffef071642 in ?? () from /usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so
#4  0x00000000004b670c in ?? ()
#5  0x00000000004b0cb3 in PyObject_Call ()
#6  0x00000000004c9faf in PyEval_EvalFrameEx ()
#7  0x00000000004c2765 in PyEval_EvalCodeEx ()
#8  0x00000000004de6fe in ?? ()
#9  0x00000000004b0cb3 in PyObject_Call ()
#10 0x00000000004f492e in ?? ()
#11 0x00000000004b0cb3 in PyObject_Call ()
#12 0x00000000004f46a7 in ?? ()
#13 0x00000000004b670c in ?? ()
#14 0x00000000004b0cb3 in PyObject_Call ()
#15 0x00000000004c9faf in PyEval_EvalFrameEx ()
#16 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#17 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#18 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#19 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#20 0x00000000004c9d8f in PyEval_EvalFrameEx ()
#21 0x00000000004c2765 in PyEval_EvalCodeEx ()
#22 0x00000000004ca099 in PyEval_EvalFrameEx ()
#23 0x00000000004c2765 in PyEval_EvalCodeEx ()
#24 0x00000000004ca099 in PyEval_EvalFrameEx ()
#25 0x00000000004c2765 in PyEval_EvalCodeEx ()
#26 0x00000000004c2509 in PyEval_EvalCode ()
#27 0x00000000004f1def in ?? ()
#28 0x00000000004ec652 in PyRun_FileExFlags ()
#29 0x00000000004eae31 in PyRun_SimpleFileExFlags ()
#30 0x000000000049e14a in Py_Main ()
#31 0x00007ffff7810830 in __libc_start_main (main=0x49dab0 <main>, argc=2, argv=0x7fffffffcb28, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffcb18) at ../csu/libc-start.c:291
#32 0x000000000049d9d9 in _start ()
```

Tried updating packages, with no help. If you help me on what can I do, I'm looking forward to doing it. Similar to #116 ?

**Comment by miquelmassot** [comment]
Found the issue: the software cura from ultimaker (used for 3d printing and slicing) installed version 4.18 of python-sip, when ROS expects 4.17. This may have broken it.
Solution: Remove cura ppa, remove any cura ppa package installed (which will remove ROS) and reinstall ROS from ppa.
