### ISSUE TITLE
rqt --perspective-file crashes on unknown plugins

### ISSUE THREAD

**Issue by lucasw** [ros-visualization/rqt#128]
[unknown_plugin.perspective.txt](https://github.com/ros-visualization/rqt/files/1756351/unknown_plugin.perspective.txt)

```
$ rqt --perspective-file unknown_plugin.perspective 
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 454, in restore_settings
    self._restore_settings_save_obsolete()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 469, in _restore_settings_save_obsolete
    self._restore_settings_unload_obsolete_callback()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 493, in _restore_settings_unload_obsolete_callback
    self._restore_settings_load_missing()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 506, in _restore_settings_load_missing
    self._load_plugin_load(instance_id, self._restore_settings_load_missing_callback)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 225, in _load_plugin_load
    plugin_descriptor = self._plugin_descriptors[instance_id.plugin_id]
KeyError: 'foo/bar'
```

I'd like to make it instead generate an error message but then go on to try to load the rest of the perspective.

One more step beyond this could be to load a dummy plugin with an error message displayed in it so it's clear that what is missing from what part of the perspective.

**Comment by lucasw** [comment]
Oops this is a job for qt_gui_core https://github.com/ros-visualization/qt_gui_core/issues/109
