### ISSUE TITLE
rqt_plot gives a trace when typing / in the topic line

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#19]
Traceback (most recent call last):
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_plot/src/rqt_plot/plot_widget.py", line 136, in on_topic_edit_textChanged
    self._topic_completer.update_topics()
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_py_common/src/rqt_py_common/topic_completer.py", line 52, in update_topics
    message_instance = roslib.message.get_message_class(topic_type)()
TypeError: 'NoneType' object is not callable

pyqt, precise, Matplot

**Comment by DorianScholz** [comment]
this now produces a warning instead of a trace
