### ISSUE TITLE
Runing rqt funciton given error message but sems to work???

### ISSUE THREAD

**Issue by 1gen100** [ros-visualization/rqt#202]
Hi guys,
I have this problem, every time a run my code with rqt_gui I get this ERROR???
But the rqt interface seems to work?

RecursivePluginProvider.discover() loading plugin "qt_gui_cpp/CppPluginProvider" failed:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/recursive_plugin_provider.py", line 57, in discover
    instance = self._plugin_provider.load(plugin_descriptor.plugin_id(), None)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 99, in load
    return class_ref()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui_cpp/cpp_plugin_provider.py", line 43, in __init__
    RosPluginlibPluginProvider(qt_gui_cpp.RosPluginlibPluginProvider_ForPlugins('qt_gui', 'qt_gui_cpp::Plugin')),
TypeError: RosPluginlibPluginProvider_ForPlugins(): argument 1 has unexpected type 'str'

**Comment by dirk-thomas** [comment]
Please provide the exact steps to reproduce as well as information about the used platform, versions and environment.

I will close the ticket for now. It can be reopened once the additional information has been added.
