### ISSUE TITLE
[ROS2] Can't run rqt

### ISSUE THREAD

**Issue by routiful** [ros-visualization/rqt#210]
I've installed ROS2 dashing lastest patch(source build) succesfully in Ubuntu 18.04. But I can't run `rqt`.
I've already used to it since last patch but also It was run when I installed it by debian packages.

I've attached error messages when I type `rqt` in terminal
```
RosPluginProvider.load(rqt_gui_py/RosPyPluginProvider) exception raised in __builtin__.__import__(rqt_gui_py.ros_py_plugin_provider, [RosPyPluginProvider]):
Traceback (most recent call last):
  File "/home/darby/ros2_ws/build/rqt_gui/src/rqt_gui/ros_plugin_provider.py", line 81, in load
    attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
ModuleNotFoundError: No module named 'rqt_gui_py'

RecursivePluginProvider.discover() loading plugin "rqt_gui_py/RosPyPluginProvider" failed:
Traceback (most recent call last):
  File "/home/darby/ros2_ws/install/qt_gui/lib/python3.6/site-packages/qt_gui/recursive_plugin_provider.py", line 60, in discover
    instance = self._plugin_provider.load(plugin_descriptor.plugin_id(), None)
  File "/home/darby/ros2_ws/build/rqt_gui/src/rqt_gui/ros_plugin_provider.py", line 91, in load
    raise e
  File "/home/darby/ros2_ws/build/rqt_gui/src/rqt_gui/ros_plugin_provider.py", line 81, in load
    attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
ModuleNotFoundError: No module named 'rqt_gui_py'
```

**Comment by routiful** [comment]
We've solved that error to use `colcon build` not include `--symlink-install` agruments.
