### ISSUE TITLE
rqt_graph is causing a trace

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#23]
I pointed the plugin at a running pr2 and selected "Nodes/Topics (active)" 
it then showed this traceback

Traceback (most recent call last):
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_graph/src/rqt_graph/ros_graph.py", line 227, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_graph/src/rqt_graph/ros_graph.py", line 254, in _generate_dotcode
    quiet=quiet)
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_graph/src/rqt_graph/dotcode.py", line 435, in generate_dotcode
    quiet=quiet)
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_graph/src/rqt_graph/dotcode.py", line 380, in generate_dotgraph
    for out_edge in node_connections.outgoing:
AttributeError: 'dict' object has no attribute 'outgoing'
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Exception AttributeError: AttributeError("'_DummyThread' object has no attribute '_Thread__block'",) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by DorianScholz** [comment]
should be fixed by my commit above, but as I did not figure out how to reproduce it, I can't be sure.
please reopen, if I'm wrong...
