### ISSUE TITLE
LookupError when running rqt_py_common tests in Windows 

### ISSUE THREAD

**Issue by azeey** [ros-visualization/rqt#230]
Possibly a regression of #228 based on the timing of the regression.

Failing build: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1580/testReport/(root)/projectroot/rqt_py_common/

Ouptut:
```
-- run_test.py: extra environment variables:
 - AMENT_PREFIX_PATH=C:/ci/ws/build/rqt_py_common/ament_index
-- run_test.py: extra environment variables to append:
 - PYTHONPATH+=C:/ci/ws/build/rqt_py_common/rosidl_generator_py
-- run_test.py: invoking following command in 'C:\ci\ws\build\rqt_py_common':
 - C:/Python38/python.exe -u -m pytest C:/ci/ws/src/ros-visualization/rqt/rqt_py_common/test -o cache_dir=C:/ci/ws/build/rqt_py_common/ament_cmake_pytest/rqt_py_common/.cache --junit-xml=C:/ci/ws/build/rqt_py_common/test_results/rqt_py_common/rqt_py_common.xunit.xml --junit-prefix=rqt_py_common
Traceback (most recent call last):
  File "C:\ci\ws\install\Lib\site-packages\ament_index_python\packages.py", line 49, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "C:\ci\ws\install\Lib\site-packages\ament_index_python\resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'launch' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\pytest\__main__.py", line 7, in <module>
    raise SystemExit(pytest.main())
  File "C:\Python38\lib\site-packages\_pytest\config\__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "C:\Python38\lib\site-packages\_pytest\config\__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python38\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Python38\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Python38\lib\site-packages\_pytest\helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\Python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Python38\lib\site-packages\_pytest\config\__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Python38\lib\site-packages\_pytest\config\__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Python38\lib\site-packages\_pytest\config\__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Python38\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "C:\ci\ws\install\Lib\site-packages\launch_testing\__init__.py", line 15, in <module>
    from . import tools
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "C:\ci\ws\install\Lib\site-packages\launch_testing\tools\__init__.py", line 18, in <module>
    from .process import launch_process
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Python38\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "C:\ci\ws\install\Lib\site-packages\launch_testing\tools\process.py", line 17, in <module>
    import launch
  File "C:\ci\ws\install\Lib\site-packages\launch\__init__.py", line 17, in <module>
    from . import actions
  File "C:\ci\ws\install\Lib\site-packages\launch\actions\__init__.py", line 17, in <module>
    from .declare_launch_argument import DeclareLaunchArgument
  File "C:\ci\ws\install\Lib\site-packages\launch\actions\declare_launch_argument.py", line 24, in <module>
    from ..frontend import Entity
  File "C:\ci\ws\install\Lib\site-packages\launch\frontend\__init__.py", line 20, in <module>
    from .parser import InvalidFrontendLaunchFileError, Parser
  File "C:\ci\ws\install\Lib\site-packages\launch\frontend\parser.py", line 31, in <module>
    from .parse_substitution import parse_substitution
  File "C:\ci\ws\install\Lib\site-packages\launch\frontend\parse_substitution.py", line 96, in <module>
    grammar_file = os.path.join(get_package_share_directory('launch'), 'frontend', 'grammar.lark')
  File "C:\ci\ws\install\Lib\site-packages\ament_index_python\packages.py", line 69, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "C:\ci\ws\install\Lib\site-packages\ament_index_python\packages.py", line 51, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'launch' not found, searching: ['C:/ci/ws/build/rqt_py_common/ament_index']"
-- run_test.py: return code 1
-- run_test.py: generate result file 'C:/ci/ws/build/rqt_py_common/test_results/rqt_py_common/rqt_py_common.xunit.xml' with failed test
-- run_test.py: verify result file 'C:/ci/ws/build/rqt_py_common/test_results/rqt_py_common/rqt_py_common.xunit.xml'
```

**Comment by dirk-thomas** [comment]
Should be fixed by ros2/launch#432.
