### ISSUE TITLE
Must build with --symlink-install

### ISSUE THREAD

**Issue by jacobperron** [ros-visualization/rqt#232]
I noticed that when building `rqt` (or any of its plugins) from source, that we must use the colcon build option `--symlink-install`. If we don't use this option or use `--merge-install`, then attempting to run `rqt` results in a Python exception that looks like the following:

```
Traceback (most recent call last):
  File "/home/jacob/ws/ros/rqt/install/bin/rqt", line 9, in <module>
    for entry_point in distribution('rqt-gui==1.0.6').entry_points:
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: rqt-gui==1.0.6
```

To reproduce:

```
mkdir -p rqt_ws/src
cd rqt_ws
git clone https://github.com/ros-visualization/rqt.git -b crystal-devel src/rqt
colcon build
```

In another shell:

```
cd rqt_ws/src
source install/setup.bash
rqt
```

This was previously reported in https://github.com/ros-visualization/rqt/issues/210, but there was no follow-up. I assume that building without `--symlink-install` should work. Correct me if I'm wrong.

**Comment by jacobperron** [comment]
Upgrading to setuptools 49.2.0 seems to have resolved the issue for me.
