### ISSUE TITLE
How to make rqt custom plugins using ROS2 eloquent?

### ISSUE THREAD

**Issue by JeongHyunLee7909** [ros-visualization/rqt#242]
Hello. I'm working on making custom plugins for my robot controller GUI.

Actually, I think there are some problems working with ROS2.

In the tutorial http://wiki.ros.org/rqt/Tutorials/Create%20your%20new%20rqt%20plugin#Install_.26_Run_your_plugin ,
they use 'catkin_make' but ros2 doesn't support that build method.

So I'm trying to modify it using 'colcon build'

I succeded to add my plugin on rqt plugins tab, but if I click it, nothing shows out but a long error message at the terminal

RosPluginProvider.load(rqt_mypkg/My Plugin) exception raised in __builtin__.__import__(rqt_mypkg.my_module, [MyPlugin]):
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_gui/ros_plugin_provider.py", line 81, in load
    attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
ModuleNotFoundError: No module named 'rqt_mypkg'

PluginManager._load_plugin() could not load plugin "rqt_mypkg/My Plugin":
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/eloquent/lib/python3.6/site-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_gui_py/ros_py_plugin_provider.py", line 64, in load
    return super(RosPyPluginProvider, self).load(plugin_id, ros_plugin_context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_gui/ros_plugin_provider.py", line 91, in load
    raise e
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_gui/ros_plugin_provider.py", line 81, in load
    attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
ModuleNotFoundError: No module named 'rqt_mypkg'

Is there anyone who knows how to make a custom plugin using ROS2 or there is an example which I can refer to?

Thanks for your help

**Comment by HighPriest** [comment]
RQT, ROS and Gazebo all suffer from mediocre documentation.
The best thing you can do is scout through the repositories and use the latest example packages as... examples.
For making a plugin package, best place would be to look into here:
https://github.com/ros-visualization/rqt_msg/tree/foxy-devel
