### ISSUE TITLE
rqt_gui issue 

### ISSUE THREAD

**Issue by Hrithik-verma** [ros-visualization/rqt#256]
When I try running "rosrun rqt_gui rqt_gui" in my terminal, I got a error :

```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/rqt_gui/rqt_gui", line 13, in <module>
    sys.exit(main.main())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 65, in main
    hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 600, in main
    plugin_manager.discover()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 125, in discover
    self._plugin_menu.add_plugin(plugin_descriptor)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_menu.py", line 82, in add_plugin
    self._enrich_action(action, action_attributes, base_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_menu.py", line 133, in _enrich_action
    action_attributes['icon'], action_attributes.get('icontype', None), base_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/icon_loader.py", line 46, in get_icon
    raise UserWarning('icon "%s" not found' % str(path))
UserWarning: icon "/opt/ros/melodic/share/rqt_virtual_joy/resource/input-gaming.png" not found
```

ROS Version- Melodic 
I have also tried "sudo apt-get install ros-melodic-rqt" its showing that I have latest version than why is there a issue .
Please help!!!

**Comment by FPSychotic** [comment]
similar error with rqt in foxy , but it change a little to line 11, the pkg is broken via apt

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as May 31st 2025, so I'm closing this.

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
