### ISSUE TITLE
rqt_dep most of the check boxes cause tracebacks when you push them and the screen then displays nothing

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#26]
Traceback (most recent call last):
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_dep/src/rqt_dep/ros_pack_graph.py", line 226, in _update_finished
    self._redraw_graph_scene()
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_dep/src/rqt_dep/ros_pack_graph.py", line 283, in _redraw_graph_scene
    self._scene.addItem(node_item)
RuntimeError: Internal C++ object (NodeItem) already deleted.
Traceback (most recent call last):
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_dep/src/rqt_dep/ros_pack_graph.py", line 226, in _update_finished
    self._redraw_graph_scene()
  File "/u/ablasdel/groovy_sandbox/rqt/rqt_dep/src/rqt_dep/ros_pack_graph.py", line 283, in _redraw_graph_scene
    self._scene.addItem(node_item)
RuntimeError: Internal C++ object (NodeItem) already deleted.

**Comment by DorianScholz** [comment]
fixed in ros-visualization/qt_gui_core@0393ebd4c92ad2cc6b9363d0529c0e918e55ad72
