### ISSUE TITLE
rqt can't load Qwt widgets

### ISSUE THREAD

**Issue by cberner** [ros-visualization/rqt#27]
When I attempted to use loadUi on a .ui file that contained a QwtCompass I got this stacktrace:

PluginManager._load_plugin() could not load plugin "ardupilot/Attitude Plugin":
Traceback (most recent call last):
  File "/opt/ros/fuerte/stacks/qt_gui_core/qt_gui/src/qt_gui/plugin_handler.py", line 84, in load
    self._load()
  File "/opt/ros/fuerte/stacks/qt_gui_core/qt_gui/src/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/fuerte/stacks/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/fuerte/stacks/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/fuerte/stacks/rqt/rqt_gui_py/src/rqt_gui_py/ros_py_plugin_provider.py", line 69, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/fuerte/stacks/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/fuerte/stacks/rqt/rqt_gui/src/rqt_gui/ros_plugin_provider.py", line 92, in load
    return class_ref(plugin_context)
  File "/home/christopher/Code/ros_experiments/ardupilot/src/ardupilot/gui.py", line 27, in __init__
    loadUi(ui_file, self._widget)
  File "/opt/ros/fuerte/stacks/python_qt_binding/src/python_qt_binding/binding_helper.py", line 150, in loadUi
    return uic.loadUi(uifile, baseinstance=baseinstance)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 221, in loadUi
    return DynamicUILoader().loadUi(uifile, baseinstance)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 71, in loadUi
    return self.parse(filename, basedir)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 929, in parse
    actor(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 770, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 748, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 459, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 748, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 502, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 748, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 215, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 176, in setupObject
    obj =  self.factory.createQObject(clsname, name, args, is_attribute)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 105, in createQObject
    classType = self.findQObjectType(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 115, in findQObjectType
    w = module.search(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/qobjectcreator.py", line 87, in search
    self._modules[module] = __import__(module, {}, {}, (cls,))
ImportError: No module named qwt_compass

**Comment by 130s** [comment]
1st of all I recommend this kind of question would be best asked on answers.ros.org.

I'm not familiar with Qwt but I doubt that loadUi, which internally uses (in your case) PyQt4's  DynamicUILoader().loadUi, might be able to handle only the classes defined in PyQt. Thus if you want to use the classes from 3rd party library in .ui file, you might need to take certain actions.

**Comment by DorianScholz** [comment]
Dear Christopher,

Isaac is right, your bug report should more likely be a question asked on answers.ros.org, but here are some hints:
rqt_gui can indeed load Qwt widgets an does so for example in one backend of the rqt_plot plugin.
In the current implementation this is not done via loadui, but only because the plotting backend is exchangeable.
You can have a look of an older implementation, where a QwtPlot was loaded via loadui:
https://github.com/ros-visualization/rqt/tree/89b6ecc4a10ac13c41eaaeac452adfefc21bd731/rqt_plot/src/rqt_plot
The data_plot.py implements a customized QwtPlot and is loaded from the Plot.ui file.

Depending on the actual goal of this plugin, you could also consider using something similar to rqt_pose_view, which uses OpenGL to display a 3D cube visualizing the orientation part of a geometry_msg/Pose.

Hopefully this was helpful. If you have further problems, it would also help to see your code, so consider putting it on github.

Cheers,
Dorian
