### ISSUE TITLE
Saving graph dotfile fails with encoding error

### ISSUE THREAD

**Issue by fake-name** [ros-visualization/rqt#275]
```
C:\Code\<project>>rqt
RosPluginProvider._parse_plugin_xml() plugin file "c:\local\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
RosPluginProvider._parse_plugin_xml() plugin file "c:\local\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
Traceback (most recent call last):
  File "c:\local\ros2-windows\Lib\site-packages\rqt_graph\ros_graph.py", line 416, in _save_dot
    handle.write(self._current_dotcode)
TypeError: write(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str'
```

I cannot provide the version because the `rqt` about dialog also fails:

```
C:\Code\<project>>rqt
RosPluginProvider._parse_plugin_xml() plugin file "c:\local\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
RosPluginProvider._parse_plugin_xml() plugin file "c:\local\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
Traceback (most recent call last):
  File "c:\local\ros2-windows\Lib\site-packages\qt_gui\about_handler.py", line 62, in show
    from qt_gui_cpp.cpp_binding_helper import qt_gui_cpp
ModuleNotFoundError: No module named 'qt_gui_cpp'
```

This is on windows, running an official build installed as described at https://docs.ros.org/en/galactic/Installation/Windows-Install-Binary.html, the [ros2-humble-20220523-windows-release-amd64.zip](https://github.com/ros2/ros2/releases/download/release-humble-20220523/ros2-humble-20220523-windows-release-amd64.zip) binaries. Likely a instance of https://github.com/ros2/ros2/issues/1139

**Comment by fake-name** [comment]
Never mind, this is a dupe of https://github.com/ros-visualization/rqt_graph/issues/67.

ROS has too many repos.
