### ISSUE TITLE
Python 3 Import Issue with Sequence

### ISSUE THREAD

**Issue by vanthome** [ros-visualization/rqt#294]
I'm on Ubuntu 22.04 and when I start rqt, it fails with:

```
 rqt
Traceback (most recent call last):
  File "/opt/ros/humble/bin/rqt", line 33, in <module>
    sys.exit(load_entry_point('rqt-gui==1.1.5', 'console_scripts', 'rqt')())
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_gui/main.py", line 94, in main
    sys.exit(Main().main())
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_gui/main.py", line 62, in main
    return super(Main, self).main(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/qt_gui/main.py", line 352, in main
    from qt_gui.application_dbus_interface import ApplicationDBusInterface
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/qt_gui/application_dbus_interface.py", line 34, in <module>
    from dbus.service import BusName, Object
  File "/home/thoppe/.local/lib/python3.10/site-packages/dbus/service.py", line 35, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

I read that this is an issue with Python >= 3.10 that must be fixed in the code.

**Comment by clalancette** [comment]
> I read that this is an issue with Python >= 3.10 that must be fixed in the code.

That's true, but it looks like this is coming from elsewhere in your system.  In particular, it looks like your `dbus` package is outdated:

```
  File "/home/thoppe/.local/lib/python3.10/site-packages/dbus/service.py", line 35, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
