### ISSUE TITLE
Fail To Launch Rqt in ROS2 Jazzy

### ISSUE THREAD

**Issue by swiz23** [ros-visualization/rqt#313]
Hi, I just install ros2 jazzy on my machine and am going through the tutorials. While trying to launch rqt in the terminal, I get this error.

```
Traceback (most recent call last):
  File "/opt/ros/jazzy/bin/rqt", line 33, in <module>
    sys.exit(load_entry_point('rqt-gui==1.6.0', 'console_scripts', 'rqt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rqt_gui/main.py", line 94, in main
    sys.exit(Main().main())
             ^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/rqt_gui/main.py", line 62, in main
    return super(Main, self).main(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/qt_gui/main.py", line 430, in main
    from qt_gui.help_provider import HelpProvider
  File "/opt/ros/jazzy/lib/python3.12/site-packages/qt_gui/help_provider.py", line 33, in <module>
    from catkin_pkg.package import InvalidPackage, parse_package
ModuleNotFoundError: No module named 'catkin_pkg.package'
```

I also checked to see that I have `python3-catkin-pkg` installed, and I do (version 1.0.0-100), so I'm not sure what I'm missing here.

**Comment by swiz23** [comment]
Did some digging into this. It's not actually a fault of rqt. There seems to be an issue with the version of `python3-catking-pkg` that the apt store installed on my machine. I was able to use apt to install a downgraded version of the package that resolved the issue (1.0.0-2 works but 1.0.0-100 did not).

```
python3-catkin-pkg:
  Installed: 1.0.0-2
  Candidate: 1.0.0-100
  Version table:
     1.0.0-100 500
        500 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
 *** 1.0.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu noble/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu noble/universe i386 Packages
        100 /var/lib/dpkg/status
```
