### ISSUE TITLE
rqt_nav_view causes a stack trace when opening a second instance

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#36]
running

```
rosrun rqt_gui rqt_gui -b pyside
```

open a rqt_nav_view plugin and then another. 
It causes this Exception

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/ros/fuerte/stacks/geometry/tf/src/tf/listener.py", line 237, in run
    self.tl.frame_graph_server = rospy.Service('~tf_frames', FrameGraph, self.frame_graph_service)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 696, in __init__
    get_service_manager().register(self.resolved_name, self)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/service.py", line 116, in register
    raise ServiceException(err)
ServiceException: service [/rqt_gui_py_node_4194/tf_frames] already registered
```

**Comment by ablasdel** [comment]
f1a271537036bca9058091b5a420921d6e23e401 fixes this issue by throwing a RuntimeException that explains the inability for two threads in a single process to subscribe to the same tf_frames service.
