### ISSUE TITLE
(PySide) rqt_cosole can't be opened

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#8]
```
PluginManager._load_plugin() could not load plugin "rqt_console/Console":
Traceback (most recent call last):
  File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui/src/qt_gui/plugin_handler.py", line 85, in load
    self._load()
  File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui/src/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/u/isaito/link/rqt_dev/git/rqt/rqt_gui_py/src/rqt_gui_py/ros_py_plugin_provider.py", line 68, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/u/isaito/link/rqt_dev/git/qt_gui_core/qt_gui/src/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/u/isaito/link/rqt_dev/git/rqt/rqt_gui/src/rqt_gui/ros_plugin_provider.py", line 95, in load
    return class_ref(plugin_context)
  File "/u/isaito/link/rqt_dev/git/rqt/rqt_console/src/rqt_console/console.py", line 58, in __init__
    self._datamodel = MessageDataModel()
  File "/u/isaito/link/rqt_dev/git/rqt/rqt_console/src/rqt_console/message_data_model.py", line 41, in __init__
    QAbstractTableModel.__init__(self)
RuntimeError: You can't initialize an object twice!
```

**Comment by ablasdel** [comment]
Fixed in e99b89e31a32842a909315a4fbef6bdadc1e9b3c
